blockworks-foundation/lite-rpc

.gitmodules, Cargo.lock, Cargo.toml
Use a `git` for dependency resolution instead of file path.
Prevents `git submodule`.
=> use git instead of path to git submodule

src/block_store.rs, src/workers/block_listenser.rs
Creating tasks to add back failed blocks to the queue makes the threads that are processing blocks free earlier to get process other blocks
=> creating seperate task for delayed addition of block

src/workers/block_listenser.rs
We don't require these metrics.
They can be acheived using the tt_recv metrics count.
=> rm fin_block and conf_block_recv

Cargo.lock, Cargo.toml, core/src/quic_connection_utils.rs, quic-forward-proxy/src/outbound/tx_forward.rs, services/src/tpu_utils/quic_proxy_connection_manager.rs
should fix https://github.com/blockworks-foundation/lite-rpc/issues/199
=> disable GSO (Generic Segmentation Offload) for all outgoing QUIC

Cargo.lock, bench/Cargo.toml, bench/src/cli.rs, bench/src/helpers.rs, bench/src/main.rs, bench/src/metrics.rs, quic-forward-proxy-integration-test/tests/quic_proxy_tpu_integrationtest.rs
Problem:
The rust bench tool used small transactions of only 179 bytes which is unrealistic.
Proposed Solution:
Add option to allow for large transactions:
`cargo run --bin bench -- --tx-count=10 |--large-transactions` (short `-L`)
transaction characteristics:
* uses memo [program](https://spl.solana.com/memo)
* 1186 bytes
* 8 account signatures
* 240 utf-chars in memo progra
* 193175 compute units
Added transaction size to metrics:
> 2023-09-29T12:27:47.830548Z  INFO bench: Run 1: Sent and Confirmed 10 tx(s) in Metric { txs_sent: 10, txs_confirmed: 10, txs_un_confirmed: 0, average_confirmation_time_ms: 546.8, average_time_to_send_txs: 0.8, average_transaction_bytes: 179.0, total_sent_time: 8.482915ms, total_transaction_bytes: 1790, total_confirmation_time: 5.468757417s } with …
=> bench: support large transactions

cluster-endpoints/src/grpc_multiplex.rs
Getting only block meta instead of whole block for finalized blocks.
=> Reduce network by only fetching block meta instead of whole block

cluster-endpoints/src/grpc_leaders_getter.rs, core/src/structures/epoch.rs, lite-rpc/src/main.rs, stake_vote/src/bootstrap.rs, stake_vote/src/epoch.rs, stake_vote/src/leader_schedule.rs, stake_vote/src/lib.rs, stake_vote/src/vote.rs
Add leader schedule bootstrap from RPC at start if the bootstrap file is missing or with the wrong epoch from the current one. This process is done before the bootstrap process of the stake_vote module to avoid to wait stake and vote account fetching.
LiteRPC now start in geyser leader schedule config without the bootstrap file.
Tested on Testnet JP os3 server during more than one epoch.
=> Bootstrap leader schedule from rpc

cluster-endpoints/src/grpc_inspect.rs, cluster-endpoints/src/grpc_subscription.rs
caused a panic - need more time to investigate
2024-01-17T20:31:42.913 app[683d392fd45368] ams [info] thread 'tokio-runtime-worker' panicked at cluster-endpoints/src/grpc_inspect.rs:59:21: 2024-01-17T20:31:42.913 app[683d392fd45368] ams [info] Error receiving block: Closed 2024-01-17T20:31:42.922 app[683d392fd45368] ams [info] 2024-01-17T20:31:42.912597Z ERROR lite_rpc: Services quit unexpectedly Err(cluster endpoint failure (Err(JoinError::Panic(Id(20), ...)), 1, [JoinHandle { id: Id(19) }, JoinHandle { id: Id(23) }])
=> remove block_debug_listen

cluster-endpoints/src/grpc_multiplex.rs
Issue was introduced with https://github.com/blockworks-foundation/lite-rpc/pull/299 merge commit.
**fix:** reset the error counter `cleanup_without_recv_full_blocks` to zero when block arrives
=> fix bug causing endless geyser restart loops

Dockerfile
```
#11 5.734   Downloaded autocfg v1.1.0
#11 5.760 error: failed to compile `cargo-chef v0.1.63`, intermediate artifacts can be found at `/tmp/cargo-installzonn1h`.
#11 5.760 To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
#11 5.760 
#11 5.760 Caused by:
#11 5.760   package `clap v4.5.0` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.73.0
#11 ERROR: executor failed running [/bin/sh -c cargo install cargo-chef --locked]: exit code: 101
#7 [run 1/4] FROM docker.io/library/debian:bookworm-slim@sha256:7802002798b0e351323ed2357ae6dc5a8c4d0a05a57e7f4d8f97136151d3d603
```
[example of broken CI](https://github.com/blockworks-foundation/lite-rpc/actions/runs/7870656050/job/2147 …
=> CI: pin chargo-chef version for MSRV=1.73

lite-rpc/src/cli.rs
Avoid display tokens as part of grpc source struct:
> 2024-02-13T11:24:34.997912Z  INFO lite_rpc: Use RPC address: https://api.testnet.rpcpool.com/dfebXXaX-XfeX-XXXX-bafX-XXccaXbabbcX    
2024-02-13T11:24:34.998102Z  INFO lite_rpc: grpc_sources:[GrpcSource http://127.0.0.1:10002 (x-token dfeb8...)]
=> obfuscate tokens

services/src/data_caching_service.rs
replacing **.expect** in
`let block = block_notifier.recv().await.expect("Should recv blocks");`
> thread 'tokio-runtime-worker' panicked at services/src/data_caching_service.rs:54:57:
Should recv blocks: Lagged(2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-03-01T06:41:49.699662Z ERROR lite_rpc: Services quit unexpectedly Err(Data caching service failed (Err(JoinError::Panic(Id(70), ...)), 1, [JoinHandle { id: Id(71) }, JoinHandle { id: Id(74) }, JoinHandle { id: Id(72) }, JoinHandle { id: Id(73) }]))
2024-03-01T06:41:50.733261Z  WARN solana_lite_rpc_cluster_endpoints::grpc_multiplex: Block channel receiver is closed - aborting
> thread 'tokio-runtime-worker' panicked at services/src/data_caching_service.rs:54:57:
Should recv blocks: Closed
=> handle Lagged blocks in data_caching

blockstore/src/block_stores/postgres/postgres_block.rs, blockstore/src/block_stores/postgres/postgres_block_store_writer.rs, blockstore/src/block_stores/postgres/postgres_transaction.rs, blockstore/tests/multiple_strategy_block_store_tests.rs, cluster-endpoints/src/grpc_inspect.rs, cluster-endpoints/src/grpc_multiplex.rs, cluster-endpoints/src/grpc_subscription.rs, cluster-endpoints/src/rpc_polling/poll_blocks.rs, core/src/solana_utils.rs, core/src/stores/block_information_store.rs, core/src/stores/data_cache.rs, core/src/stores/subscription_store.rs, core/src/stores/tx_store.rs, core/src/structures/notifications.rs, core/src/structures/produced_block.rs, core/src/structures/proxy_request_format.rs, core/src/structures/transaction_sent_info.rs, lite-rpc/src/bridge.rs, lite-rpc/src/bridge_pubsub.rs, lite-rpc/src/postgres_logger/mod.rs, lite-rpc/src/rpc_pubsub.rs, quic-forward-proxy-integration-test/tests/quic_proxy_tpu_integrationtest.rs, services/src/data_caching_service.rs, services/src/transaction_service.rs, services/src/tx_sender.rs
- remove calls to Pubkey::default()
- use Signature for .signature instead of String
- use Hash for recent_blockhash instead of String
- refactor reading of compute_budget instructions
- move message serialization
=> from grpc block ProduceBlock mapping - Performance+Typing

lite-rpc/src/main.rs
Reproduction:
* run two lite-rpc processes
Stdout/stderr shows this
> Error: 
> 2024-03-15T11:13:43.087231Z ERROR lite_rpc: Services quit unexpectedly Err(Support Services Ok(Err(Prometheus exited unexpectedly: Ok(Err(Address already in use (os error 48))))))    
Error:
=> fix error log on service issue

accounts/src/account_service.rs, blockstore/tests/blockstore_integration_tests.rs, cluster-endpoints/src/endpoint_stremers.rs, cluster-endpoints/src/grpc_multiplex.rs, cluster-endpoints/src/grpc_subscription.rs, cluster-endpoints/src/json_rpc_subscription.rs, cluster-endpoints/src/rpc_polling/poll_blocks.rs, core/src/stores/block_information_store.rs, core/src/structures/block_info.rs, core/src/structures/mod.rs, core/src/types.rs, lite-rpc/src/main.rs, lite-rpc/src/service_spawner.rs, services/src/data_caching_service.rs
changes dependency of block_information_store to block stream->block info stream; this should propagate finalized block information faster
the important change is inside the `.listen` method: look for _block_information_store_block_info_ as this is updated from blockinfo_stream
=> use geyser blockmeta to progress finalizedslot

Dockerfile
PostgreSQL connection fails using TLS with this with recent docker image:
> 2024-03-20T12:21:52.444 app[7842094c44d538] ams [info] PostgreSQL session cache: Identity
2024-03-20T12:21:52.444 app[7842094c44d538] ams [info] Caused by:
2024-03-20T12:21:52.444 app[7842094c44d538] ams [info] error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
ErrorStack([Error { code: 50856204, library: "digital envelope routines", function: "inner_evp_generic_fetch", reason: "unsupported", file: "../crypto/evp/evp_fetch.c", line: 373, data: "Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()" }]))
workaround:
disable postgres with `PG_ENABLED=false`
=> fix postgres ssl algo issue - Algorithm (RC2-40-CBC : 0)

cluster-endpoints/src/grpc_multiplex.rs
will call full block mapper as late as possible
=> optimize mapping of produced block

services/src/tpu_utils/tpu_connection_manager.rs
Prediction is that this has no negative effect but reduces memory use a lot.
=> experiment: reduce number of source endpoints to 1

services/src/quic_connection.rs
These days many of nodes have custom scrpts to block traffic which is not originating from gossip node.
=> moving unable to connection to a node using quic from warning to debug

cluster-endpoints/src/grpc_multiplex.rs, cluster-endpoints/src/rpc_polling/poll_blocks.rs, core/src/commitment_utils.rs, core/src/stores/subscription_store.rs, core/src/structures/block_info.rs, lite-rpc/src/bridge.rs, lite-rpc/src/bridge_pubsub.rs, lite-rpc/src/main.rs, lite-rpc/src/rpc.rs, lite-rpc/src/rpc_pubsub.rs, lite-rpc/src/start_server.rs, quic-forward-proxy-integration-test/Cargo.toml, stake_vote/src/bootstrap.rs, tests/client.test.ts, yarn.lock
Updating signatures for few methods,
Fixing websockets signatures.
Removing unwanted tests
=> Gixing websocket subscriptions for signatures and slot

Cargo.lock, bench/Cargo.toml, bench/src/benches/confirmation_rate.rs, bench/src/benches/confirmation_slot.rs, bench/src/benches/mod.rs, bench/src/benches/rpc_interface.rs, bench/src/benches/tx_status_websocket_collector.rs, bench/src/benchnew.rs, bench/src/service_adapter_new.rs, benchrunner-service/README.md, benchrunner-service/src/args.rs, benchrunner-service/src/main.rs, benchrunner-service/src/postgres/metrics_dbstore.rs, migrations/create_benchrunner.sql
replace get_signature_statuses polling by websocket _blockSubscribe_
the tx status progression gets tracked by a thread maintained in `tx_status_websocket_collector` which exposes the status as a shared concurrent map.
=> benchrunner status from websocket
