blockworks-foundation/lite-rpc

.gitmodules, Cargo.lock, Cargo.toml, src/cli.rs, src/context.rs, src/main.rs, src/rpc.rs
- [use git instead of path to git submodule](https://github.com/blockworks-foundation/lite-rpc/pull/1)
- `cargo fmt` and `cargo fix`
=> cargo fix and fmt

src/main.rs, src/rpc.rs
Adding way to free context and join threads at the end.
=> Adding a correct way to free the RPC context

Cargo.lock, Cargo.toml, README.md, src/cli.rs, src/context.rs, src/main.rs, src/pubsub.rs, src/rpc.rs
Implementing websockets for onSignature and onSlot
=> Adding ws subscriptions

Cargo.lock, Cargo.toml, src/bridge.rs, src/main.rs, src/workers/metrics_capture.rs, src/workers/tx_sender.rs
=> Rm proc info

Cargo.lock, Cargo.toml, src/bridge.rs, src/cli.rs, src/main.rs, src/tpu_manager.rs, src/workers/tx_sender.rs, tests/workers.rs
Adding identity to the connection cache for tpu client.
=> adding identity to the tpu client, connection cache

src/main.rs, src/workers/block_listenser.rs
=> Some changes in block listner

src/main.rs
=> Setting runtime at start

tests/client.test.ts
=> block test

.gitignore, bench/src/helpers.rs, benches/create_n_users.bench.ts
- random memo for each tx
- optimized create_n_users bench and ignore out.json
=> optimize create n users.bench

src/workers/block_listenser.rs, src/workers/tpu_utils/tpu_connection_manager.rs, src/workers/tx_sender.rs
Reconnect if creating unistream fails
=> Reconnect to the quic server

migrations/create.sql, src/workers/block_listenser.rs, src/workers/postgres.rs
note wip, this does not implement parsing (the more popular) legacy compute budget instruction
=> implement parsing of compute budget instructions

bench/Cargo.toml, bench/src/helpers.rs
on Mac the file location is pointing "/Users/Alice/Library/Application Support/solana/id.json" but it should be "/Users/Alice/.config/solana/id.json"
=> Keypair file location macos fix

Cargo.lock, core/src/block_store.rs, lite-rpc/src/bridge.rs, lite-rpc/src/main.rs
=> no restart

core/src/block_processor.rs, core/src/block_store.rs, core/src/leader_schedule.rs, lite-rpc/src/bridge.rs, services/src/block_listenser.rs, services/src/tpu_utils/tpu_service.rs
add `.context("...")` to give move details about failing RPC calls
=> debugging context rpc calls

Cargo.lock, core/src/keypair_loader.rs, core/src/lib.rs, lite-rpc/src/cli.rs, lite-rpc/src/main.rs, quic-forward-proxy/Cargo.toml, quic-forward-proxy/README.md, quic-forward-proxy/src/inbound/proxy_listener.rs, quic-forward-proxy/src/main.rs, quic-forward-proxy/src/outbound/tx_forward.rs, quic-forward-proxy/src/proxy.rs, quic-forward-proxy/src/util.rs
Changes based on feedback here https://github.com/blockworks-foundation/lite-rpc/pull/164#discussion_r1313079727
=> Quic proxy gm improvements

lite-rpc/src/main.rs, quic-forward-proxy/src/cli.rs, quic-forward-proxy/src/main.rs
=> allow for hostname in '--proxy-listen-addr' and '--quic-proxy-addr'

docs/architecture.md, docs/rpcv2.md
Change consensus domain name to Validator.
Simplify some diagrams
=> Rpc doc update

.github/workflows/test.yml, .github/workflows/test_with_validator.yml, quic-forward-proxy-integration-test/tests/quic_proxy_tpu_integrationtest.rs, rust-toolchain.toml, test.bash
GitHub Actions:
* use sscache + cache
* split rust test and test with validator
=> Improve ci GitHub actions

docs/architecture.md, docs/rpcv2.md
Add RPC subscriptions in rpcv2 and architecture docs.
=> Add RPC subscriptions

tests/client.test.ts
=> add epoch info test for process and finalized

Cargo.lock, cluster-endpoints/Cargo.toml
https://github.com/blockworks-foundation/geyser-grpc-connector/issues/3
=> fix: panic on geyser close, multiplex bug

cluster-endpoints/src/grpc/gprc_accounts_streaming.rs
=> use auto reconnect

bench/src/bench1.rs, bench/src/benches/confirmation_slot.rs, bench/src/benches/rpc_interface.rs, bench/src/helpers.rs, bench/src/lib.rs
Consolidate duplicate helper functions
=> refactor: use VersionedTransaction in benchmarks
